### ISSUE TITLE
Establish positions/mobility of UEs and eNBs

### ISSUE THREAD

**Issue by khaledhassan** [khaledhassan/eel6591-project#2]
Relevant lines of lena-x2-handover-measures.cc: 231-248

- [x] Implement correct mobility model for UEs (Random Walk)
- [x] Put eNBs at a position that makes sense (see eNB_positioning branch) --got hexagonal working, might be easier/make more sense to use simple grid
- [x] eNB grid positioning
  - [x] Replace GridPositionAllocator with a for loop so we can move the eNBs up by ~~~30m~~~ 15m or so
  - [x] decide if want to use hex grid
- [x] Install handover algorithm (using rsrp, see handoverAlgorithm branch)

**Comment by khaledhassan** [comment]
There is a function
```void
LteHelper::AttachToClosestEnb (NetDeviceContainer ueDevices, NetDeviceContainer enbDevices)``` in lte-helper.cc:1018 that could help us automatically attach the right ue to the right enb

**Comment by khaledhassan** [comment]
[] Implement correct mobility model for UEs (Random Walk)
[] Put eNBs at a position that makes sense (hex grid?)

**Comment by khaledhassan** [comment]
Handover algorithm code:
```
  lteHelper->SetHandoverAlgorithmType ("ns3::A3RsrpHandoverAlgorithm");
  lteHelper->SetHandoverAlgorithmAttribute ("Hysteresis",
                                            DoubleValue (3.0));
  lteHelper->SetHandoverAlgorithmAttribute ("TimeToTrigger",
                                            TimeValue (MilliSeconds (256)));
```
Put this after:
```
  Config::SetDefault ("ns3::LteEnbPhy::TxPower", DoubleValue (enbTxPowerDbm));
  enbLteDevs = lteHelper->InstallEnbDevice (enbNodes);
  ueLteDevs = lteHelper->InstallUeDevice (ueNodes);
```

**Comment by khaledhassan** [comment]
Hex grid for eNBs:
see file ```lte-hex-grid-enb-topology-helper.cc```

**Comment by slichtenheld** [comment]
Waypoint model may be better to trigger handovers, don't think random walk is the best model here.

**Comment by khaledhassan** [comment]
That's true, but the paper used the random walk model. Perhaps we can do a comparison between them as a part of our report. I think/hope we can get the random walk working with real values for the eNB distances, such as the ones they used in the paper
